# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerrorAttackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iyear', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=30)),
                ('crit_1', models.BinaryField()),
                ('cirt_2', models.BinaryField()),
                ('cirt_3', models.BinaryField()),
                ('attacktype_1', models.CharField(max_length=40)),
                ('attacktype_2', models.CharField(max_length=40)),
                ('attacktype_3', models.CharField(max_length=40)),
                ('targettype_1', models.CharField(max_length=40)),
                ('targetsubtype_1', models.CharField(max_length=40)),
                ('targettype_2', models.CharField(max_length=40)),
                ('targetsubtype_2', models.CharField(max_length=40)),
                ('targettype_3', models.CharField(max_length=40)),
                ('targetsubtype_3', models.CharField(max_length=40)),
                ('gname_1', models.CharField(max_length=60)),
                ('gname_2', models.CharField(max_length=60)),
                ('gname_3', models.CharField(max_length=60)),
                ('weaptype_1', models.CharField(max_length=60)),
                ('weapsubtype_1', models.CharField(max_length=60)),
                ('weaptype_2', models.CharField(max_length=60)),
                ('weapsubtype_2', models.CharField(max_length=60)),
                ('weaptype_3', models.CharField(max_length=60)),
                ('weapsubtype_3', models.CharField(max_length=60)),
                ('weaptype_4', models.CharField(max_length=60)),
                ('weapsubtype_4', models.CharField(max_length=60)),
                ('nkill', models.IntegerField()),
                ('nwound', models.IntegerField()),
            ],
        ),
    ]
