# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrorattackrecord',
            name='cirt_2',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='terrorattackrecord',
            name='cirt_3',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='terrorattackrecord',
            name='crit_1',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='terrorattackrecord',
            name='iyear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='terrorattackrecord',
            name='nkill',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='terrorattackrecord',
            name='nwound',
            field=models.IntegerField(default=-1),
        ),
    ]
