# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170319_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrorattackrecord',
            name='nkill',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='terrorattackrecord',
            name='nwound',
            field=models.FloatField(default=-1.0),
        ),
    ]
